name: sql_data_helper
description: A dart package to organize our sql data
version: 1.0.3
homepage: https://github.com/Flerma98
repository: https://github.com/Flerma98/dart_sql_data_helper
issue_tracker: https://github.com/Flerma98/dart_sql_data_helper/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter: